foo:
  foo version 21
democonfigclient:
  message=hello spring io
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/
server:
  port: 8881
  
  
# routes to serviceId
# routes to url
# zuul.routes.api-a-url.path=/userapi/**
# zuul.routes.api-a-url.url=http://localhost:8881/
#eureka.client.serviceUrl.defaultZone=http://localhost:8880/eureka/
